### ISSUE TITLE
Running Que with Docker

### ISSUE THREAD

**Issue by sigfrid** [que-rb/que#242]
I'm using `1.0..0.beta3` with a Rails 5.2 app running natively on my Mac and Postgres running on Docker.

Unfortunately, with such setup, I'm not able to run any migration since they fail to execute
```
pg_dump -s -x -O -f /Users/sig/Code/bi/db/structure.sql bi_development
```

What it'd work is 

```
docker exec CONTAINER_NAME pg_dump -s -x -O -f /Users/sig/Code/bi/db/structure.sql bi_development
```

Now, I'm looking for a way to overwrite the `pg_dump` command but I can't find it.

Any ideas?

Thanks

**Comment by sigfrid** [comment]
If anyone needs it, as a workaround, I currently fixed it by adding
`alias pgdump='docker exec  CONTAINER_NAME pgdump'` to my `~/.bash_profile`.

**Comment by siegy22** [comment]
You have your postgres inside your docker container, which means you need to either execute the `pg_dump` from within the container (as you did) or if you have a postgres client installed (on your mac) you can remotely connect to the database which is running inside the docker container.

Maybe useful: 
- https://ksearch.wordpress.com/2012/09/28/how-to-backup-a-remote-postgresql-db-and-restore-it-locally/
- https://www.postgresql.org/docs/11/libpq-envars.html

I'm going to close this issue, because it's not related to que at all.
Feel free to reopen it if you don't think so.
