### ISSUE TITLE
Reconsider the introduction of a default maximum_retry_count

### ISSUE THREAD

**Issue by hlascelles** [que-rb/que#251]
Que 1.x introduces maximum_retry_count, after which the job stops. 

From `https://github.com/chanks/que/blob/master/docs/error_handling.md`

_There is a maximum_retry_count option for jobs. It defaults to 15 retries, which with the default retry interval means that a job will stop retrying after a little more than two days._

This is a great addition, but the fact that it is has a default that stops the job is concerning to me. Major versions can of course include breaking changes, but we only noticed it by chance. 

One of the best things about Que is its resilience and the fact that jobs aren't lost (which we experienced constantly with Resque). I expect the change is related to the presence of the history table, but I'd say that is a bonus, not the main job flow.

Can I request the default be changed to "retry forever" in Que 1.x?

**Comment by airhorns** [comment]
@hlascelles do you think that might be kind of surprising for developers? To me the new default makes sense because if a job has failed 15 times in a row over two days, it seems reasonable to assume thats because of some systemic failure, and that it's unlikely to succeed without something external changing. It think it'd be prudent for que to protect itself (and the system) by not retrying indefinitely, as if there is ever a systematically failing job and enough of them enqueued, they will pile up and consume all worker resources. I think the default of this "self-healing" (and also I guess less correct-ness oriented) approach makes sense so that developers don't accidentally shoot themselves in the foot with the above problem. Jobs like the `que-scheduler` jobs I think are the exceptions to the rule?

Both sidekiq and delayed_job both have a fixed number of retries with exponential backoff as well.

**Comment by siegy22** [comment]
I agree that "retrying forever" is kind of a dangerous default. I can't imagine having a job run for more than 2 days and suddenly succeed again.

In general I'm not a fan of (blindly) retrying jobs. 

In the applications I built, I let certain (really few) jobs automatically retry on certain errors. E.g. if there was a network error when trying to connect to a 3rd party API. But in general I want my job to fail if there's an exception. 😄 
That's just my opinion, but the current default feels pretty good to me.

@chanks What are your thoughts on this?

**Comment by chanks** [comment]
Yeah, I'm not a big fan of retrying forever, particularly as a default. I
do think it makes sense to support that behavior as a configuration option,
though I don't remember offhand if 1.0 already supports that.

**Comment by hlascelles** [comment]
Yes, good points all. 

I was surprised to learn the default for the gem [delayed_job](https://github.com/collectiveidea/delayed_job) is complete job deletion - not something we could tolerate.

OK, I'll close this knowing that the 1.x branch _by default_ will keep failed (expired) jobs in a dead letter queue which will aid morning manual retries :+1:.
