### ISSUE TITLE
Named queues don't work in ActiveJob

### ISSUE THREAD

**Issue by adeeb1** [que-rb/que#266]
I'm trying to integrate Que with Rails' ActiveJob, and it seems to be working fine with the exception of the queue name. I found on [this comment](https://github.com/que-rb/que/issues/179#issuecomment-284004802) that named queue support was removed from ActiveJob. My infrastructure has workers listening on different queues, and I use the queue name to determine which workers will process the job. The lack of support for named queues in ActiveJob is critically important to me, so I cannot use the ActiveJob integration.

Are there any plans to support named queues in ActiveJob?

**Comment by morgoth** [comment]
@adeeb1 There is an old PR opened to support this https://github.com/rails/rails/pull/32157 however I don't know if this indeed should be the way to go following the comment you mentioned

**Comment by siegy22** [comment]
I can't see a reason why we shouldn't re-add the named queue support, as @chanks said `... Now I think this was a mistake on my part ...`. 

Multiple (and named) queueing support is [still here](https://github.com/que-rb/que/tree/master/docs#multiple-queues) in que, just not in the activejob adapter. I think we should probably push this to get the activejob named queueing support. 

But with these decisions I'm always cautious. @chanks Would you like to share your opinion here or is [your comment](https://github.com/que-rb/que/issues/179#issuecomment-284004802) enough? It already says that we should re-add support 😄

**Comment by chanks** [comment]
So, this all revolves around job priorities. Que has represented job priority as an integer since the very beginning, and I chose to represent priorities as a number because it made querying for the most important job(s) simple and efficient.

Named queues were added a bit later because of an edge case one user had in the early days, where different types of jobs needed to be worked by entirely different processes (some jobs required more memory or access to ImageMagick or something like that). Unfortunately, it seems much more common in the Rails community to use named queues to organize jobs by priority (having a "low-priority" queue, an "urgent" queue, or whatever). I say unfortunately because this is much less efficient for Que to query - when priorities are numeric Que can do a simple query for the N most important jobs regardless of their priority level, whereas if one insists on using named queues for that then Que needs to first query the "urgent" queue, then maybe query the "high-priority" queue, etc. And of course when someone (who wasn't me) first wrote the Que adapter for ActiveJob, they added support for specifying the queue names, because why not.

So this resulted in a lot of people using named queue blindly (because it was what the ActiveJob API exposed) for a purpose they weren't really designed for. At one point I wanted to stop this by removing named queues altogether and instead just making it possible to have multiple job tables in the same DB for the rare cases where multiple job queues were actually necessary. I guess I was hoping that this would push users to use numeric priorities the way I felt they should, but maybe that's wrong-headed and it's better to give the users what they want, I don't know. I guess if that were to happen, then some people would run into performance issues, and when they complained then the answer would be to nudge them to remove ActiveJob as a middleman and just use Que the way it's meant to be used.

**Comment by morgoth** [comment]
@chanks Thank you for your explanation.
There are valid usecases for separating jobs by queue name, which que supports - `--queue-name` on CLI.
When coming from Rails via AJ adapter it's surprising that setting queue name doesn't work.

As it goes for concerns about performance, maybe que could add an index on "queue" column by default? WDYT @siegy22

**Comment by defkode** [comment]
I agree with @morgoth stand point, Ideal fix for me is to remove `ActiveJob::QueueAdapters::QueAdapter` from rails completely, put it in [Que](https://github.com/que-rb/que) and require when needed.

**Comment by siegy22** [comment]
IMO if we support a thing as named queues, we should also expose it to the activejob adapter.

I'm not really certain about the index on the `queue` column as @morgoth suggested, because this would have some impact on people that run que without using activejob/named queues. If someone uses que with activejob, they can add the index themselves, or what do you think? 😄 

If I have the time, I'm going to push this to get https://github.com/rails/rails/pull/32157 merged.

**Comment by chanks** [comment]
The queue name is already covered in the main index of the jobs table, but that doesn't solve the fundamental problem, which is that checking for new jobs using numeric priorities requires 1 query, while checking for new jobs across N different queues requires up to N queries.

**Comment by morgoth** [comment]
This is now supported in Rails and should be available on next 6.0.x Rails release

**Comment by siegy22** [comment]
Thank you @morgoth, sorry for not responding in such a long time, I've had a snowboard accident and was in the hospital. 😓 

We should probably add a notice in the README with which activejob version this will work?

**Comment by morgoth** [comment]
Hey @siegy22, sorry to hear that, hope you're good now.

It will be available in versions >= 6.0.3 of Rails, which still is not released.

BTW, is there any plan to release version 1.0 of que? Is there anything blocking it?

**Comment by siegy22** [comment]
@morgoth We're almost there: https://github.com/que-rb/que/milestone/1

**Comment by morgoth** [comment]
@siegy22 Rails 6.0.3 is released, so this is now fixed in this stable release.
I guess the issue can be closed now

**Comment by siegy22** [comment]
Nice!
