### ISSUE TITLE
What does this part of the docs mean?

### ISSUE THREAD

**Issue by i2chris** [que-rb/que#272]
Apologies if this isn't the right place for this, but I don't understand what this sentence in the docs means:

> be aware that you'll lose the ability to finish the job in the same transaction as other database operations

This is during the discussion of Active Job.

What does finish the job mean here? Does it mean actually run the job in the same transaction?

Thanks

**Comment by airhorns** [comment]
One of Que's major features is the ability to atomically commit job changes & the job's success at the same time such that either both or neither happen. In other job processing systems (like those using Redis), because the changes the job makes to the database are in a different system than the record of the job's state (in redis), you can't guarantee that you can change both at the same time. This means a job might commit it's changes to the database, then crash or get killed, at which point the job running system will see it as a failure and retry it, when really it has already done its work. This can be bad! See https://github.com/que-rb/que/tree/master/docs#writing-reliable-jobs for more details.

When using ActiveJob, you aren't able to use this feature of Que, because of the way the two different things are implemented. ActiveJob jobs will still finish and report themselves as complete when all is working well, but they will lack the atomicity guarantees Que gives you if you were use it in the way the reliable jobs doc suggests. Any ActiveRecord models mutated during the execution of the job will happen in a different database transaction than the transaction that marks the job as completed in the database. If you were using the Que API and the `#finish` method inside a transaction you start in the job, the job would be marked as complete in that transaction which brings all the normal transactional guarantees. 

It totally depends on what the job is doing, but, its usually not a big deal to retry jobs, and it's a good practice to make them idempotent anyways.

**Comment by i2chris** [comment]
Thanks for that.

I'm currently using Sidekiq + Redis to manage jobs.  Their WebUI is useful for letting me start failed jobs when I want to after fixing a problem.  How would you do this with Que?

**Comment by i2chris** [comment]
Thanks for your help.
