### ISSUE TITLE
Dying que process due to Thread.current.abort_on_exception = true

### ISSUE THREAD

**Issue by meceo** [que-rb/que#305]
We experienced an issue with terminating the que processes due to an exception raised. We have a flow where we raise a custom error, to catch it higher, log some things and reraise again. On the first reraise, the que process dies. That's very unfortunate because the rollbar monitoring tool, which relies on catching an exception, has no possibility to catch the exception and inform us. In my opinion, the que workers should be able to continue after the custom exception raised.

However, in the que code it seems like you have forced different behaviour on purpose:
https://github.com/que-rb/que/blob/master/lib/que/worker.rb#L42

Can you please elaborate?

**Comment by dmolesUC** [comment]
Que novice and Rollbar non-user here, but:

1. is your job code called from that worker thread? can you just override `Thread.current.abort_on_exception =` in your job code?
2. assuming it's set to `false`, and the exception only kills this specific worker thread, and Rollbar is clever enough to catch uncaught exceptions on all threads, I suspect Que still isn't going to be in good shape, because it's not (AFAICT) written to expect worker threads to die out from under it.
3. how is your custom error getting out of `Que::Worker#work_loop` to crash the thread? shouldn't it be rescued [here](https://github.com/que-rb/que/blob/master/lib/que/worker.rb#L125)?
4. can you do the Rollbar reporting from inside your job code, cf. [Rollbar::ActiveJob](https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar/plugins/active_job.rb)?

**Comment by ZimbiX** [comment]
I'm having trouble understanding your setup.

- I take it the exception is raised while executing a job?
- Does the custom exception inherit from `StandardError`? Other root exception classes are not always captured when you expect them to be - see [this article](https://www.honeybadger.io/blog/ruby-exception-vs-standarderror-whats-the-difference/)
- At which point are you trying to submit the exception to Rollbar?
- Where and how are you re-raising? Is it for the Rollbar submission, or unrelated?

If it helps, in our apps, we use a Que middleware for reporting errors to Sentry - no re-raising required:

```ruby
# frozen_string_literal: true

require 'dex_provider_bridge/system/import'

module DexProviderBridge
  module Que
    module JobMiddleware
      class ErrorReporting
        include DexProviderBridge::System::Import['error_reporting']

        def call(job)
          yield

          capture_job_error(job) if job.failed? && job.report_errors?
        end

        private

        def capture_job_error(job)
          error_reporting.capture_exception(job.error, extra_context: extra_context(job))
        end

        def extra_context(job)
          {
            job_name: job.job_name,
            error_count: job.error_count,
            args: job.que_attrs[:args],
          }
        end
      end
    end
  end
end
```

```ruby
# Invoked in the order they are registered
middlewares = [
  # ...
  DexProviderBridge::Que::JobMiddleware::ErrorReporting.new, # Job errors in Sentry
]
middlewares.each do |middleware|
  Que.job_middleware.push(middleware)
end
```

**Comment by ZimbiX** [comment]
@meceo Without detail to the contrary, I'm considering my response as having resolved this issue. Please feel free to reopen if you have more information for us.
