### ISSUE TITLE
Creating new workers slows down the previous ones

### ISSUE THREAD

**Issue by dima4p** [que-rb/que#331]
Hi,

I have a delayed job that processed the lines of files.
When I start only one worker for this job, processing of one line takes approx. 1 ms.
With two workers each spends approx. 2 ms per line.
With 4 workers - approx. 4 ms. 

And, yes, I see 4 processes in the system.

What can be the reason? 

With best regards, 
Dmitry

**Comment by thomasvdpol** [comment]
I am reasonably sure this isn't Que related, check if there's a file lock that prevents job 2 from reading the file while job 1 is reading it, that'd explain the almost too neat delays.

**Comment by dima4p** [comment]
> I am reasonably sure this isn't Que related, check if there's a file lock that prevents job 2 from reading the file while job 1 is reading it, that'd explain the almost too neat delays.

There is no common file. Each job reads its own file. But both add records to the same table in the database. If I start several workers (que processes), the problem disappeared.

**Comment by ZimbiX** [comment]
Ah, I was initially confused because you didn't specify that you were using worker _threads_ xP

This sounds like it might be a question of worker threads vs worker processes with a CPU intensive workload. I'd think the behaviour of Que you're seeing is expected, as it's an inherent part of Ruby threading - iirc, one Ruby process can't use more than a core, as this would demonstrate:

```bash
ruby -e '4.times { Thread.new { loop { 8**100 } }; sleep'
```

![Screenshot from 2022-02-16 23-13-20](https://user-images.githubusercontent.com/2916331/154262426-9078fb2f-693e-4c1d-a29b-9357d13d8283.png)

In this screenshot, htop shows 100%, meaning it's using a full core, not all my cores.

With a CPU intensive workload (rather than say a HTTP intensive one), Que worker threads will give no benefit, and you'd need to use more Que worker _processes_ instead.

**Comment by dima4p** [comment]
Now there is another problem I have started 7 runners. One with `-p 10,20,30,50,50` and 6 with `-p any`. And have created 5 jobs with priority 90. But actually only 2 are running. What can be the reason?
![ParseLogTimesJob_20220218_125128](https://user-images.githubusercontent.com/25119/154680544-a326866e-62a0-4ae0-b175-23dd725e17fa.png)
![ParseLogTimesJob_20220218_125312](https://user-images.githubusercontent.com/25119/154680546-df208635-1742-41ea-91a2-223ab544512b.png)

**Comment by ZimbiX** [comment]
If you only have a very small number of jobs currently in the queue, try decreasing the buffer size. We saw that kind of issue early on in us using Que - we had one long job which which was blocking idle worker processes from picking up the couple of quick jobs which were in the queue behind it. iirc, because a worker process by default allocates several jobs to itself (the [buffer](https://github.com/que-rb/que/tree/master/docs#minimum-buffer-size-and-maximum-buffer-size)) as a performance optimisation. We should probably document this behaviour. And remove the minimum buffer size option, as I don't think that one's actually used anymore.

**Comment by dima4p** [comment]
> If you only have a very small number of jobs currently in the queue, try decreasing the buffer size. We saw that kind of issue early on in us using Que - we had one long job which which was blocking idle worker processes from picking up the couple of quick jobs which were in the queue behind it. iirc, because a worker process by default allocates several jobs to itself (the [buffer](https://github.com/que-rb/que/tree/master/docs#minimum-buffer-size-and-maximum-buffer-size)) as a performance optimisation. We should probably document this behaviour. And remove the minimum buffer size option, as I don't think that one's actually used anymore.

  Thank you. It seems that helps. 
  But why not to have default values for the parameters being 0?
> 
> In future, for a separate problem, please create a separate issue ;)
OK

**Comment by ZimbiX** [comment]
> But why not to have default values for the parameters being 0?

Performance is significantly improved using the buffer

**Comment by ZimbiX** [comment]
I was just about to create an issue to document the preference of threads/processes depending on workload, but it's [already documented](https://github.com/que-rb/que/tree/master/docs#managing-workers). Did you just miss this, or could its clarity be improved?

**Comment by dima4p** [comment]
> I was just about to create an issue to document the preference of threads/processes depending on workload, but it's [already documented](https://github.com/que-rb/que/tree/master/docs#managing-workers). Did you just miss this, or could its clarity be improved?

I did miss.

**Comment by dima4p** [comment]
But I still did not get the meaning of the "buffer". This thing must be explained in more details. Together with the keys --maximum-buffer-size and --minimum-buffer-size.
