### ISSUE TITLE
Que v1 should state that it's incompatible with ruby 3

### ISSUE THREAD

**Issue by kyrofa** [que-rb/que#364]
It seems well-known from the various issues here that Que v1 is incompatible with Ruby 3, and such compatibility is being introduced in Que v2. That's fine, no problem. However, would you please consider adding `required_ruby_version` in the v1 gemspec to be less than Ruby 3? It would be far more friendly to Que users than pretending that it works when it doesn't. I just spent more time than I care to admit diving through error logs trying to figure out what broke. And that's after all the work to update my app to Ruby 3, which I now need to revert. I wouldn't have started that if I knew my gems were incompatible. Happy to propose, just want to get some buy-in if possible.

**Comment by ZimbiX** [comment]
Sorry to hear that!

I'm all for making this more frictionless, but I'm not sure that this is a great solution - to add that, we'd have to release a new version of Que 1.x. I'm not too familiar with `required_ruby_version`, but if I'm correctly understanding what it does, you'd only see the error if you first updated your app to that new version of Que 1.x before trying to update to Ruby 3. With Que 2 released now (in beta), I imagine most people would be upgrading to that rather than a later 1.x version.

Regardless, we probably should do that and add something about the required Ruby version to the readme too.

**Comment by ZimbiX** [comment]
Completed in [v1.4.1](https://github.com/que-rb/que/releases/tag/v1.4.1)
